name: app_af_motors
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.0.0
  cloud_firestore: ^5.0.0
  http: ^1.2.0
  intl: ^0.19.0
  pdf: ^3.10.8
  printing: ^5.11.1
  path_provider: ^2.1.2
  share_plus: ^7.2.2
  url_launcher: ^6.2.5
  file_picker: ^8.0.0
  image_picker: ^1.0.7
  firebase_storage: 12.4.10
  mobile_scanner: ^5.2.3
  cupertino_icons: ^1.0.8
  easy_mask: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png